### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by jamesonrader** [jkeen/forever-chat-imessage-export#8]
Running `node try.js` I get the following error:

```
> sudo node try.js
Password:
internal/modules/cjs/loader.js:895
  throw err;
  ^

Error: Cannot find module '/Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node'
Require stack:
- /Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/node_modules/sqlite3/lib/sqlite3.js
- /Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/lib/open-db.js
- /Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/index.js
- /Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/try.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/lib/open-db.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/node_modules/sqlite3/lib/sqlite3.js',
    '/Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/lib/open-db.js',
    '/Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/index.js',
    '/Users/Home/Projects/imessage-predictor/ML/iMessage-Export/forever-chat-imessage-export/try.js'
  ]
}
```

**Comment by jamesonrader** [comment]
Kinda silly, just needed to run `yard add sqlite3`. I figured everything would already be in the `yarn.lock` file. Javascript is not my expertise, clearly
